name: dbk cicd pipeline

on:
  workflow_dispatch:
#       - 'ncr_cicd/**'


jobs:
  DBK-PIPELINE-JOB:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      env_name: ${{ steps.step1.outputs.env_name }}
    steps:
      - id: step1
        run: |
           echo "Running on branch ${{ github.ref }}"
           if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "::set-output name=env_name::main"
           elif [ "${{ github.ref }}" = "refs/heads/development" ]; then
            echo "::set-output name=env_name::develop"
           fi
  DEMO-JOB:
    runs-on: ubuntu-latest
    needs: DBK-PIPELINE-JOB
    steps:
      - env:
          env_name: ${{needs.DBK-PIPELINE-JOB.outputs.env_name}}
        run: echo "i'm $env_name"

  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.PROD_USERNAME }}
          password: ${{ secrets.PROD_PASS }}
        run: |
          docker images

