
name: release pipeline 

on:
  workflow_run:
    workflows: ["Tag pipeline"]
    types:
      - completed
jobs:
  fetch-env-name:
    runs-on: ubuntu-latest
    outputs:
      env_name: ${{ steps.branch_check.outputs.env_name }}
    steps:
      - name: Some check on branch
        id: branch_check
        run: |
          echo "Running on branch ${{ github.ref }}"
          if [ "${{ github.ref }}" = "refs/heads/tag" ]; then
            echo "env_name=tag_branch" >> "$GITHUB_OUTPUT"
          elif [ "${{ github.ref }}" = "refs/heads/release" ]; then
            echo "env_name=release_branch" >> "$GITHUB_OUTPUT"
          elif [ "${{ github.ref }}" = "refs/heads/uat" ]; then
            echo "env_name=uat" >> "$GITHUB_OUTPUT"
          else
             echo "Undefined envs"
          fi    

