name: dbk cicd pipeline

on:
  workflow_dispatch:
  
jobs:
  DBK-PIPELINE-JOB:
    runs-on: ubuntu-latest
    outputs:
      env_name: ${{ steps.step1.outputs.env_name }}
    steps:
      - id: step1
        run: |
           echo "Running on branch ${{ github.ref }}"
           if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "env_name=Production" >> "$GITHUB_OUTPUT"
           elif [ "${{ github.ref }}" = "refs/heads/develop" ]; then
            echo "env_name=develop" >> "$GITHUB_OUTPUT"
           else
            echo "no variables"
           fi

  login:
    runs-on: ubuntu-latest
    needs: DBK-PIPELINE-JOB
    environment: ${{ needs.fetch-env-name.outputs.env_name }}
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          

