
name: dbk cicd pipeline

on:
  workflow_dispatch:
  
jobs:

name: dbk cicd pipeline

on:
  workflow_dispatch:
  
jobs:
  DBK-PIPELINE-JOB:
    runs-on: ubuntu-latest
    outputs:
      env_name: ${{ steps.step1.outputs.env_name }}
    steps:
      - id: step1
        run: |
           echo "Running on branch ${{ github.ref }}"
           if [ "${{ github.ref }}" = "refs/heads/tag" ]; then
            echo "env_name=tag_branch" >> "$GITHUB_OUTPUT"
           elif [ "${{ github.ref }}" = "refs/heads/release" ]; then
            echo "env_name=release_branch" >> "$GITHUB_OUTPUT"
           else
            echo "no variables"

  build:
    name: Create Release
    runs-on: ubuntu-latest
    needs: DBK-PIPELINE-JOB
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{github.run_number}}
          release_name: Release ${{ needs.DBK-PIPELINE-JOB.outputs.env_name }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
