name: Tag pipeline

on:
  workflow_dispatch:
#   push:
#     branches:
#       - tag

jobs:
  fetch-env-name:
    runs-on: ubuntu-latest
    outputs:
      env_name: ${{ steps.branch_check.outputs.env_name }}
    steps:
      - name: Some check on branch
        id: branch_check
        run: |
          echo "Running on branch ${{ github.ref }}"
          if [ "${{ github.ref }}" = "refs/heads/tag" ]; then
            echo "env_name=tag_branch" >> "$GITHUB_OUTPUT"
          elif [ "${{ github.ref }}" = "refs/heads/develop" ]; then
            echo "env_name=dev" >> "$GITHUB_OUTPUT"
          elif [ "${{ github.ref }}" = "refs/heads/uat" ]; then
            echo "env_name=uat" >> "$GITHUB_OUTPUT"
          else
             echo "v1"
          fi    
  build:
    name: Create Release
    runs-on: ubuntu-latest
    needs: fetch-env-name
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          commitish: tag
          tag_name: ${{github.run_number}}
          release_name: Release ${{ needs.fetch-env-name.outputs.env_name }} ${{github.run_number}}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: true
          prerelease: false
      - name: Create annotation for build error
        run: ls
      - uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }} 
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./*.zip
          asset_name: asset.zip
          asset_content_type: application/zip

      - uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}


