name: tagv1
on:
  push:
    branches:
      - tag
      - main
      
    
jobs:
  release-project:
    name: Release static site to github release
    runs-on: ubuntu-latest
    needs: upload-artifact-tag
    steps:
      - name: Download the content
        uses: actions/download-artifact@v2
        with:
          name: static-site
      - name: Archive site content
        uses: thedoctor0/zip-release@master
        with:
          filename: site.zip
      - name: Create Github Release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: ./site.zip
          asset_name: site-v${{ github.run_number }}.zip
          asset_content_type: application/zip
    
  upload-artifact-tag:
    name: Create upload artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: static-site
          path: /
