name: workflow_02
on:
    repository_dispatch:
        types: [ workflow_01 ]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggering Wokflow 2"
      - name: Checkout
        uses: actions/checkout@v2
